apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-index-pvc
  namespace: safs
  labels:
    app: code-index
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 100Gi
